lib/watery_web/router.ex
defmodule WateryWeb.Router do
  use WateryWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {WateryWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", WateryWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/plants", PlantController
    post "/plants/:id", PlantController, :water
  end

  # Other scopes may use custom stacks.
  # scope "/api", WateryWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: WateryWeb.Telemetry
    end
  end
end

lib/watery_web/templates/page/index.html.heex
<h1>Plants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Frequency</th>
      <th>Last watered</th>

      <th><%= link "Water all", to: Routes.plant_path(@conn, :water, :all), method: :post %></th>
    </tr>
  </thead>
  <tbody>
<%= for plant <- @plants do %>
    <tr style={color(plant)}>
      <td><%= plant.name %></td>
      <td>Every <%= pretty_frequency(plant.frequency) %></td>
      <td><%= pretty_days_since_watered(plant) %></td>

      <td>
        <span><%= link "Edit", to: Routes.plant_path(@conn, :edit, plant) %></span>
        
          <%= link to: Routes.plant_path(@conn, :water, plant), method: :post do %>
            <%# <%= FontAwesome.icon("droplet", type: "solid", class: "h-4 w-4") %>
            Water
          <% end %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Plant", to: Routes.plant_path(@conn, :new) %></span>